version: '3.1'
services:
    web:
        container_name: web_core
        build: docker/web
        ports:
            - "8080:80"
        volumes:
            - ./symfony/:/code
        links:
            - php
            
    php:
        container_name: php_core
        build: docker/php
        volumes:
            - ./symfony/:/code
        links:
            - db
            
    db:
        container_name: db_core
        build: docker/db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "password"
        volumes:
            - ./docker/db/data:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin_core
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
